USE [master]
GO
/****** Object:  Database [CrudClient]    Script Date: 27/10/2020 18:42:45 ******/
CREATE DATABASE [CrudClient]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CrudClient', FILENAME = N'/var/opt/mssql/data/CrudClient.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CrudClient_log', FILENAME = N'/var/opt/mssql/data/CrudClient_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [CrudClient] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CrudClient].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CrudClient] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CrudClient] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CrudClient] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CrudClient] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CrudClient] SET ARITHABORT OFF 
GO
ALTER DATABASE [CrudClient] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CrudClient] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CrudClient] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CrudClient] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CrudClient] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CrudClient] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CrudClient] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CrudClient] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CrudClient] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CrudClient] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CrudClient] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CrudClient] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CrudClient] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CrudClient] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CrudClient] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CrudClient] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CrudClient] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CrudClient] SET RECOVERY FULL 
GO
ALTER DATABASE [CrudClient] SET  MULTI_USER 
GO
ALTER DATABASE [CrudClient] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CrudClient] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CrudClient] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CrudClient] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CrudClient] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'CrudClient', N'ON'
GO
ALTER DATABASE [CrudClient] SET QUERY_STORE = OFF
GO
USE [CrudClient]
GO
/****** Object:  User [dev]    Script Date: 27/10/2020 18:42:46 ******/
CREATE USER [dev] FOR LOGIN [dev] WITH DEFAULT_SCHEMA=[dbo]
GO
USE [master]
GO
ALTER DATABASE [CrudClient] SET  READ_WRITE 
GO
